# -*- coding: utf-8 -*-
"""casestudy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16nIQxieDSEAFfWSXUzUtlpC2-rqBMFbF

# 1.1 Generate a list of 100 simulated sensor readings.
#    Each reading should be a tuple: (timestamp_str, device_id, device_type, location, value).
#    - timestamp_str: Format as 'YYYY-MM-DD HH:MM:SS'
#    - device_id: A unique ID for each reading (e.g., 'DEV001', 'DEV002', etc., up to 100 unique IDs).
#    - device_type: Randomly chosen from DEVICE_TYPES.
#    - location: Randomly chosen from LOCATIONS.
#    - value: Random float within READING_RANGES for its device_type (round to 2 decimal places).
# Store these in a list called 'raw_sensor_data'.

# Your code for Task 1.1 here:
"""

import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
# We'll imagine this is sensor data from various devices.
DEVICE_TYPES = ['Temperature_Sensor', 'Humidity_Sensor', 'Pressure_Sensor', 'Light_Sensor']
LOCATIONS = ['Lab1', 'Lab2', 'OfficeA', 'OfficeB', 'Warehouse']
READING_RANGES = {
    'Temperature_Sensor': (18.0, 30.0), # Celsius
    'Humidity_Sensor': (30.0, 80.0),   # Percentage
    'Pressure_Sensor': (980.0, 1030.0),# hPa
    'Light_Sensor': (100, 1000)        # Lux
}
raw_sensor_data=[]
for i in range(100):
       time_stamp=datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
       device_id=f'DEV{i+1:03d}'
       device_type=random.choice(DEVICE_TYPES)
       location=random.choice(LOCATIONS)
       value=round(random.uniform(READING_RANGES[device_type][0],READING_RANGES[device_type][1]),2)
       raw_sensor_data.append((time_stamp,device_id,device_type,location,value))
print(raw_sensor_data)

"""# 1.2 From 'raw_sensor_data', create a list named 'temperature_readings' containing only the readings
#     where 'device_type' is 'Temperature_Sensor'.
#     Each item in 'temperature_readings' should be a dictionary with keys:
#     'timestamp', 'device_id', 'location', 'temperature_celsius'.

# Your code for Task 1.2 here:


"""

import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
# We'll imagine this is sensor data from various devices.
DEVICE_TYPES = ['Temperature_Sensor', 'Humidity_Sensor', 'Pressure_Sensor', 'Light_Sensor']
LOCATIONS = ['Lab1', 'Lab2', 'OfficeA', 'OfficeB', 'Warehouse']
READING_RANGES = {
    'Temperature_Sensor': (18.0, 30.0), # Celsius
    'Humidity_Sensor': (30.0, 80.0),   # Percentage
    'Pressure_Sensor': (980.0, 1030.0),# hPa
    'Light_Sensor': (100, 1000)        # Lux
}
temperature_readings = []

for reading in raw_sensor_data:
    if reading[2] == "Temperature_Sensor":
        temp_dict = {
            "timestamp": reading[0],
            "device_id": reading[1],
            "location": reading[3],
            "temperature_celsius": reading[4]
        }
        temperature_readings.append(temp_dict)

# Display first 5 temperature readings
print("\nFirst 5 Temperature Readings:")
for reading in temperature_readings[:5]:
    print(reading)

"""# 1.3 Create a set named 'unique_locations' containing all unique locations from 'raw_sensor_data'."""

import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
# We'll imagine this is sensor data from various devices.
DEVICE_TYPES = ['Temperature_Sensor', 'Humidity_Sensor', 'Pressure_Sensor', 'Light_Sensor']
LOCATIONS = ['Lab1', 'Lab2', 'OfficeA', 'OfficeB', 'Warehouse']
READING_RANGES = {
    'Temperature_Sensor': (18.0, 30.0), # Celsius
    'Humidity_Sensor': (30.0, 80.0),   # Percentage
    'Pressure_Sensor': (980.0, 1030.0),# hPa
    'Light_Sensor': (100, 1000)        # Lux
}
unique_locations = set()

for reading in raw_sensor_data:
    unique_locations.add(reading[3])

print("\nUnique Locations:")
print(unique_locations)

"""# 1.4 Create a dictionary named 'device_stats' where keys are 'device_type' and values are
#     a tuple: (min_value, max_value) observed for that device type across all readings.
#     Initialize with sensible large/small values.

# Your code for Task 1.4 here:


"""

import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
# We'll imagine this is sensor data from various devices.
DEVICE_TYPES = ['Temperature_Sensor', 'Humidity_Sensor', 'Pressure_Sensor', 'Light_Sensor']
LOCATIONS = ['Lab1', 'Lab2', 'OfficeA', 'OfficeB', 'Warehouse']
READING_RANGES = {
    'Temperature_Sensor': (18.0, 30.0), # Celsius
    'Humidity_Sensor': (30.0, 80.0),   # Percentage
    'Pressure_Sensor': (980.0, 1030.0),# hPa
    'Light_Sensor': (100, 1000)        # Lux
}
device_stats = {}

for device in DEVICE_TYPES:
    device_stats[device] = (float("inf"), float("-inf"))

for reading in raw_sensor_data:
    device_type = reading[2]
    value = reading[4]

    min_value, max_value = device_stats[device_type]

    if value < min_value:
        min_value = value
    if value > max_value:
        max_value = value
    device_stats[device_type] = (min_value, max_value)

print(device_stats)

""" 1.5: Advanced Indexing and Slicing (Lists and Strings)
print("\n--- Task 1.5: Advanced Indexing and Slicing (Lists and Strings) ---")

# Let's use 'raw_sensor_data' and create a sample string for these tasks.
sample_string = "PythonProgrammingIsFun"

"""

import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
# We'll imagine this is sensor data from various devices.
DEVICE_TYPES = ['Temperature_Sensor', 'Humidity_Sensor', 'Pressure_Sensor', 'Light_Sensor']
LOCATIONS = ['Lab1', 'Lab2', 'OfficeA', 'OfficeB', 'Warehouse']
READING_RANGES = {
    'Temperature_Sensor': (18.0, 30.0), # Celsius
    'Humidity_Sensor': (30.0, 80.0),   # Percentage
    'Pressure_Sensor': (980.0, 1030.0),# hPa
    'Light_Sensor': (100, 1000)        # Lux
}
sliced_readings_1 = raw_sensor_data[9:20]

sliced_readings_2 = raw_sensor_data[::5]

print(sliced_readings_1)
print(sliced_readings_2)

""".5.1 List Slicing: Extract elements from the 10th to the 20th (inclusive) from 'raw_sensor_data'.
#       Store the result in 'sliced_readings_1'.
#       Then, extract every 5th reading from 'raw_sensor_data' starting from the beginning.
#       Store the result in 'sliced_readings_2'.

"""

import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
# We'll imagine this is sensor data from various devices.
DEVICE_TYPES = ['Temperature_Sensor', 'Humidity_Sensor', 'Pressure_Sensor', 'Light_Sensor']
LOCATIONS = ['Lab1', 'Lab2', 'OfficeA', 'OfficeB', 'Warehouse']
READING_RANGES = {
    'Temperature_Sensor': (18.0, 30.0), # Celsius
    'Humidity_Sensor': (30.0, 80.0),   # Percentage
    'Pressure_Sensor': (980.0, 1030.0),# hPa
    'Light_Sensor': (100, 1000)        # Lux
}
sorted_readings = sorted(raw_sensor_data, key=lambda x: x[4])

print(sorted_readings)

"""1.5.2 String Slicing: Extract the substring "Programming" from 'sample_string'.
#       Store the result in 'substring_1'.
#       Then, extract the substring "nohtyP" (the reverse of "Python") from 'sample_string' using slicing.
#       Store the result in 'substring_2'.

"""

import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
# We'll imagine this is sensor data from various devices.
DEVICE_TYPES = ['Temperature_Sensor', 'Humidity_Sensor', 'Pressure_Sensor', 'Light_Sensor']
LOCATIONS = ['Lab1', 'Lab2', 'OfficeA', 'OfficeB', 'Warehouse']
READING_RANGES = {
    'Temperature_Sensor': (18.0, 30.0), # Celsius
    'Humidity_Sensor': (30.0, 80.0),   # Percentage
    'Pressure_Sensor': (980.0, 1030.0),# hPa
    'Light_Sensor': (100, 1000)        # Lux
}
fifth_reading_device_type = raw_sensor_data[4][2]

device_type_suffix = fifth_reading_device_type[-6:]

print(fifth_reading_device_type)
print(device_type_suffix)

"""1.5.3 Mixed Slicing: Access the 'device_type' of the 5th reading in 'raw_sensor_data' using indexing.
#       Store it in 'fifth_reading_device_type'.
#       Then, from 'fifth_reading_device_type', extract the last 6 characters (e.g., 'Sensor' from 'Temperature_Sensor').
#       Store it in 'device_type_suffix'.

"""

import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
# We'll imagine this is sensor data from various devices.
DEVICE_TYPES = ['Temperature_Sensor', 'Humidity_Sensor', 'Pressure_Sensor', 'Light_Sensor']
LOCATIONS = ['Lab1', 'Lab2', 'OfficeA', 'OfficeB', 'Warehouse']
READING_RANGES = {
    'Temperature_Sensor': (18.0, 30.0), # Celsius
    'Humidity_Sensor': (30.0, 80.0),   # Percentage
    'Pressure_Sensor': (980.0, 1030.0),# hPa
    'Light_Sensor': (100, 1000)        # Lux
}
def get_readings_by_location(readings_list, target_location):
    result = []

    for reading in readings_list:
        if reading[3] == target_location:
            result.append(reading)

    return result

"""# --- Task 2: Writing and Using Functions in Python ---
print("\n--- Task 2: Function Definitions and Usage ---")

2.1 Write a function `get_readings_by_location(readings_list, target_location)`
#     that takes the 'raw_sensor_data' list and a 'target_location' string.
#     It should return a list of all readings (as tuples) for that specific location.

# Your code for Task 2.1 here:
"""

import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
# We'll imagine this is sensor data from various devices.
DEVICE_TYPES = ['Temperature_Sensor', 'Humidity_Sensor', 'Pressure_Sensor', 'Light_Sensor']
LOCATIONS = ['Lab1', 'Lab2', 'OfficeA', 'OfficeB', 'Warehouse']
READING_RANGES = {
    'Temperature_Sensor': (18.0, 30.0), # Celsius
    'Humidity_Sensor': (30.0, 80.0),   # Percentage
    'Pressure_Sensor': (980.0, 1030.0),# hPa
    'Light_Sensor': (100, 1000)        # Lux
}
def get_readings_by_location(readings_list, target_location):
    result = []

    for reading in readings_list:
        if reading[3] == target_location:
            result.append(reading)

    return result

"""# 2.2 Write a function `calculate_average_temperature(temp_data_list)`
#     that takes the 'temperature_readings' list (list of dictionaries).
#     It should calculate and return the average temperature. Return 0.0 if the list is empty.

# Your code for Task 2.2 here:



"""

import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
# We'll imagine this is sensor data from various devices.
DEVICE_TYPES = ['Temperature_Sensor', 'Humidity_Sensor', 'Pressure_Sensor', 'Light_Sensor']
LOCATIONS = ['Lab1', 'Lab2', 'OfficeA', 'OfficeB', 'Warehouse']
READING_RANGES = {
    'Temperature_Sensor': (18.0, 30.0), # Celsius
    'Humidity_Sensor': (30.0, 80.0),   # Percentage
    'Pressure_Sensor': (980.0, 1030.0),# hPa
    'Light_Sensor': (100, 1000)        # Lux
}
def calculate_average_temperature(temp_data_list):
    if len(temp_data_list) == 0:
        return 0.0

    total = 0

    for reading in temp_data_list:
        total += reading["temperature_celsius"]

    return total / len(temp_data_list)

"""# 2.3 Write a function `generate_report_line(reading_dict)`
#     that takes a single temperature reading dictionary.
#     It should return a formatted string like:
#     "[{timestamp}] Device {device_id} at {location}: {temperature_celsius}°C"

# Your code for Task 2.3 here:

"""

import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
# We'll imagine this is sensor data from various devices.
DEVICE_TYPES = ['Temperature_Sensor', 'Humidity_Sensor', 'Pressure_Sensor', 'Light_Sensor']
LOCATIONS = ['Lab1', 'Lab2', 'OfficeA', 'OfficeB', 'Warehouse']
READING_RANGES = {
    'Temperature_Sensor': (18.0, 30.0), # Celsius
    'Humidity_Sensor': (30.0, 80.0),   # Percentage
    'Pressure_Sensor': (980.0, 1030.0),# hPa
    'Light_Sensor': (100, 1000)        # Lux
}
def generate_report_line(reading_dict):
    return f"[{reading_dict['timestamp']}] Device {reading_dict['device_id']} at {reading_dict['location']}: {reading_dict['temperature_celsius']}°C"