# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YUuEfFMw95icDGRltU3cF1Kh0jZPko3Q
"""

import numpy as np
arr=np.arange(1,9)
print(arr)

arr=np.arange(1,13)
print(arr.reshape(3,4))

arr=np.array([[1,2],[4,5],[6,7]])
print(arr.shape)
print(arr.size)

arr=np.full((4,3),6)
print(arr)

arr=np.eye(6)
print(arr)

arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.T)
print(arr[0])
print(arr[0],arr[1])

arr=np.array([[1,2,3],[4,5,6],[7,8,9],[12,34,56]])
new_array=arr.reshape(3,4)
print(new_array)

arr=np.array([12,34,56,46,8,99,9,76])
print(arr[1:3])
print(arr[1:5:2])
print(arr[3:6])

arr=np.array([[1,2,3],
             [4,5,6],
              [5,7,8]])
print(arr[1:3,2:4])

arr=np.array([[1,2,3],[4,5,6]])
print(np.sqrt(arr))
print(np.square(arr))
print(np.sin(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.power(arr,6))

from __future__ import print_function
import numpy as np
print(np.random.rand())
print(np.random.rand(5))
print(np.random.randint(1,20,5))

print(5&3)

import numpy as np
a = np.array([12,11,34])
b = np.array([2,4,5])
print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)
print("Floor Division:", a//b)
print("Modulus:", a%b)
print("Power:", a**2)

import numpy as np
arr = np.array([2, 5, 6, 17, 20])
print("Original Array:", arr)
print("\nSquare Root:", np.sqrt(arr))
print("Square:", np.square(arr))
print("Cube:", np.power(arr, 3))
arr2 = np.array([-54, -11, 18, 22, 35])
print("\nAbsolute Value:", np.abs(arr2))
print("\nExponential:", np.exp(arr))
print("\nNatural Log:", np.log(arr))
print("Log Base 10:", np.log10(arr))
print("\nSine:", np.sin(arr))
print("Cosine:", np.cos(arr))
print("Tangent:", np.tan(arr))
decimal = np.array([34.3, 45.3, 84.4, 7.3])
print("\nRounded Values:", np.round(decimal))

print("Ceiling:", np.ceil(decimal))
print("Floor:", np.floor(decimal))

import numpy as np
marks = np.array([54, 80, 45, 34, 99, 88, 56])
print("Original Array:", marks)
print("Sorted Array:", np.sort(marks))
print("Sum:", np.sum(marks))
print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Max:", np.max(marks))
print("Min:", np.min(marks))
print("Range:", np.ptp(marks))
print("Standard Deviation:", np.std(marks))
print("Variance:", np.var(marks))
print("Idx of Maximum:", np.argmax(marks))
print("Idx of Minimum:", np.argmin(marks))
print("22th Percentile:", np.percentile(marks, 22))
print("54th Percentile:", np.percentile(marks, 54))
print("75th Percentile:", np.percentile(marks, 75))