# -*- coding: utf-8 -*-
"""pandas and calculus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bZ84xJpNf1Ldws4DYHwdYmgZNNy5x8xt
"""

import numpy as np
import sympy as sp
x,y=sp.symbols('x y')
def f(X):
  return X**2
h=1e-6
slope_at_4=(f(4+h)-f(4))/h
print("the value of f'(4) is:",round(slope_at_4,6),'(exact=8)')

expr = x**2
deriv = sp.diff(expr, x)
print('d/dx (x**2) =', deriv)
print("Symbolic f'(3) =", deriv.subs(x, 3))

def g(x):
    return x**3 + 2*x
h=1e-6
slope_at_2=(g(h+2)-g(2))/h
print("slope at 2 ie f'(x)",round(slope_at_2,4))
by=x**3+2*x
deriv=sp.diff(by,x)
print(deriv)
print(deriv.subs(x,2))

f2 = x**2 + 3*x*y + y**2
print('df/dx =', sp.diff(f2, x))
print('df/dy =', sp.diff(f2, y))

grad = [sp.diff(f2, v) for v in (x, y)]
print('grad f =', grad)
grad_at = [g.subs({x: 1, y: 2}) for g in grad]
print('grad f at (1, 2) =', grad_at)

X = np.random.randn(4, 3)
Y = np.random.randn(4, 1)
W1 = np.random.randn(3, 5) * 0.3
W2 = np.random.randn(5, 1) * 0.3
z1 = X @ W1
h  = np.maximum(0, z1)
y_hat = h @ W2
loss = ((y_hat - Y) ** 2).mean()
print('Initial loss:', round(loss, 4))

dy   = 2 * (y_hat - Y) / Y.size
dW2  = h.T @ dy
dh   = dy @ W2.T
dz1  = dh * (z1 > 0)
dW1  = X.T @ dz1
print('dW1 shape:', dW1.shape, '(matches W1)')
print('dW2 shape:', dW2.shape, '(matches W2)')

"""pandas

"""

import pandas as pd
import numpy as np
#series 1d data
s=pd.Series([20,30,40,50],index=['a','b','c','d'])
print(s)
#data frame 2d data
data={
    'name':['nigama','keerthana','ravi'],
    'age':[18,19,23],
    'rollno':[98,99,13]
}
df=pd.DataFrame(data)
print(df)

array=np.array([[1,2],[2,4],[4,5]])
df_from_array=pd.DataFrame(array,columns=['a','b'])
print(df_from_array)

print(df.loc[0])#access rows by lable
print(df.iloc[0:2])#accessing rows by position
print(df['name'])
print(df['age'])
print(df[df['age']>20])

data_dirty={
    'name':['nigama',None,'ravi'],
    'age':[None,19,23],
    'rollno':[98,99,45]
}
df_data_dirty=pd.DataFrame(data_dirty)
print(df_data_dirty)
print(df_data_dirty.dropna())
print(df_data_dirty.fillna({'name':'unknown','age':df_data_dirty['age'].mean(),'roolno':0}))

print(df_data_dirty.isnull())

df['next']=df['age']+1
print(df)
df_Rename=df.rename(columns={'name':'firstname'})
print(df_Rename)
print(df.sort_values(by='rollno',ascending=False))
df['AgeGroup'] = df['age'] > 30
print(df.groupby('AgeGroup')['rollno'].mean())

np.random.seed(1)
num_rows=10
df_synth=pd.DataFrame({
    'id':np.arange(1,num_rows+1),
    'score':np.random.randint(50, 100,size=num_rows),
    'passed':np.random.choice([True,False],size=num_rows)
})
print(df_synth)

