# -*- coding: utf-8 -*-
"""week2-functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mTR-JuaO8nnlGZSB2DqrCQhGDO_AAgyc
"""

def greet():
    print("Hello! Welcome to Python Functions.")
greet()

def greet_person(name):
  print(f"hello {name}")
greet_person("nigama")

def greet_user(name="ooo"):
  print(f"hello {name}")
greet_user()
greet_user("nigama")

def print_info(**info):
  print("user info")
  for key,value in info.items():
    print(f"{key}:{value}")
print_info(name="nigama",roll=98,branch="cse")
print_info(name="gfgd",roll=47,branch="ece")

def show_details(*args, **kwargs):
    print("Args:", args)
    print("Kwargs:", kwargs)

show_details(1, 2, 3, name="nigama", city="kmm")

def multiply(a, b):
    return a * b

def square(n):
    return multiply(n, n)

print("Square of 12:", square(12))

from functools import reduce
numbers=[1,2,3]
squared_numbers=list(map(lambda x:x**2,numbers))
odd_numbers=list(filter(lambda x:x%2!=0,numbers))
reduce_numbers=reduce(lambda x,y:x+y,numbers)
print(squared_numbers)
print(odd_numbers)
print(reduce_numbers)

fruits=['apple','banana',]
print(fruits)
print("first one:",fruits[0])
fruits.append('juanc')
print(fruits)
fruits.remove('apple')
print(fruits)

