# -*- coding: utf-8 -*-
"""week-3modules and exceptions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16iJ2xSgkuM7GNosz3k-10jux0PyQavFk
"""

from datetime import(datetime)
bday=int(input("enter your bday"))
now=datetime.today().year
age=now-bday
print(age)

try:
  x=int(input("enter the number"))
  print("your number is:",x)
except ValueError:
  print("invalid numbere")

from ast import Num
try:
  x=int(input("enter number"))
  a=20/x
except ValueError:
  print("invalid number")
except ZeroDivisionError:
  print("zero divion errorr")
else:
  print("result:",a)
finally:
  print("completed")

try:
  x=int("ten")
  b=30/0
except (ValueError,ZeroDivisionError) as e:
  print("invalid number")
else:
  print("result:",b)

def check_age(age):
  if age<0:
    raise ValueError("age cant be -ve")
  else:
    print("your age is,age")
  try:
    check_age(-5)
  except ValueError as e:
    print("invalid age",e)

def divide(a, b):
    print(f"Dividing {a} by {b}")  # Debug info
    return a / b

print(divide(10, 2))

def check_age(age):
    if age < 0:
        raise ValueError("Age cannot be negative!")
    else:
        print("Age is valid.")

try:
    check_age(-5)
except ValueError as e:
    print("Caught an exception:", e)