# -*- coding: utf-8 -*-
"""week1(inputs and outputs).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hrzTGgWYYUFIMEujx85zQ7-F0Upqk-ty
"""

name="nigama"
age="18"
print(f"person {name} is {age}")

"""person nigama is 18"""

print("{1} is a {0}".format("girl","nigama"))

"""nigama is a girl"""

print("welcome to python")

"""welcome to python"""

print(24)
print(50)

"""24
50
"""

name="nigama"
print(name)

"""nigama"""

a=10
b=15
print(a)
print(b)

"""10
15
"""

a=10
b=20
print(a)
print(b)

"""10
20
"""

a=10
b=3
print(a)
print(b)

"""10
3
"""

name="nigama"
age=18
print(f"this is {name} and is {age} years old")

"""this is nigama and is 18 years old"""

name="nigama"
print(f"{name}")

"""nigama"""

name="nigama"
print("name is %s"%(name))

a=5
b=4
print(a)
print(b)

x = 2
print(x)

num = 25
print(num)

value = 15.522222
print(type(value))

name = "nigama"
marks = 92
print(f"{name} got {marks}")

print("Python", "Programmi", "Language")

a = 10
b = 20
print("Sum =", a + b)

name = "Rahul"
print(name * 3)

age=input("enter age")
print(age)

x=10
y=20
print(f"{x},{y}")

name = "Amit"
cgpa = 8.75
print(name)
print(cgpa)